AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Plantilla SAM para el backend de Identera con FastAPI y DynamoDB

Globals:
  Function:
    Timeout: 30
    MemorySize: 512

Resources:
  # Definición de la Tabla DynamoDB
  IdenteraTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: IdenteraDB
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  # Definición de la función Lambda que correrá FastAPI
  FastApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/
      Handler: main.handler
      Runtime: python3.10
      Architectures:
        - x86_64
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: IdenteraDB
      Policies:
        # Esto le da permisos a la Lambda para leer y escribir en la tabla definida arriba
        - DynamoDBCrudPolicy:
            TableName: !Ref IdenteraTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
        RootApi:
          Type: Api
          Properties:
            Path: /
            Method: ANY

Outputs:
  ApiUrl:
    Description: "URL del API Gateway para el entorno Prod"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
